server:
  port: 9090
  
spring:
  application:
    name: API-GATEWAY
  
    
  cloud: 
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/authService/**
          filters:
            - AuthenticationFilter
            
        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/customerService/** , /v3/api-docs/customerService
          filters:
            - AuthenticationFilter
        
        - id: items-service
          uri: http://localhost:8083
          predicates:
            - Path=/itemService/** , /v3/api-docs/itemService
          filters:
            - AuthenticationFilter
            
        - id: cart-service
          uri: http://localhost:8084
          predicates:
            - Path=/cartService/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true